version: '3'

services:
  db:
    container_name: foodgram_database
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: itsmeemichka/foodgram_backend
    command: bash -c "python manage.py migrate --no-input && python manage.py collectstatic --no-input && gunicorn --bind 0.0.0.0:8000 --workers=3 foodgram_backend.wsgi"
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: itsmeemichka/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: foodgram_gateway
    image: itsmeemichka/foodgram_gateway
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend

volumes:
  pg_data:
  static:
  media:
