# Generated by Django 4.2.7 on 2023-12-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('first_name',)},
        ),
        migrations.AlterModelOptions(
            name='usersubs',
            options={'ordering': ('user',)},
        ),
    ]
