# Generated by Django 4.2.7 on 2023-12-20 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_usersubs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubs',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
